app/urls.py
from django.urls import path
from . import views

app_name='app'

urlpatterns = [
#    path('login/', views.Login.as_view(), name='login'),
#    path('logout/', views.Logout.as_view(), name='logout'), 
    path('', views.index, name='index'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('analyze/<int:pk>/', views.analyze, name='analyze'),
    path('new_file/', views.new_file, name='new_file'), 
]

yency/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
#    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.core.validators import FileExtensionValidator
import os

# Create your models here.

class FileUpload(models.Model):
    """
    ファイルのアップロード
    """
    title = models.CharField(default='年月', max_length=100)
    upload_file = models.FileField(upload_to='csv', validators=[FileExtensionValidator(['csv',])])
    created_at = models.DateField(auto_now_add=True)
    analyzed_file = models.FileField(upload_to='xlsx', validators=[FileExtensionValidator(['xlsx',])], blank=True, null=True)

    def __str__(self):
        return self.title

    def upload_file_name(self):
        """
        アップロードファイルパスからファイル名のみを取得するカスタムメソッド
        """
        path = os.path.basename(self.upload_file.name)
        return path

    def analyzed_file_name(self):
        """
        解析後ファイルパスからファイル名のみを取得するカスタムメソッド
        """
        path = os.path.basename(self.analyzed_file.name)
        return path

app/forms.py
from django import forms
from .models import FileUpload
from django.core.files.storage import default_storage
from django.contrib.auth.forms import AuthenticationForm

# Create the form class.
class LoginForm(AuthenticationForm):
    '''
    ログインフォーム
    '''
    def __init__(self, *args, **kwargs):
       super().__init__(*args, **kwargs)
       # htmlの表示を変更可能にします
       self.fields['username'].widget.attrs['class'] = 'form-control'
       self.fields['password'].widget.attrs['class'] = 'form-control'

class FileUploadForm(forms.ModelForm):
    '''
    アップロードフォーム
    '''
    class Meta:
        model = FileUpload
        fields = ('title', 'upload_file',)

app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views import generic
from django_pandas.io import pd
from django.core.files import File
from django.core.files.storage import default_storage
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import(LoginView, LogoutView)
from .forms import LoginForm
from .models import FileUpload
from .forms import FileUploadForm
from .kakeibo import Analyze

# Create your views here.
class Login(LoginView):
    """ログインページ"""
    form_class = LoginForm
    template_name = 'app/login.html'


class Logout(LoginRequiredMixin, LogoutView):
    """ログアウトページ"""
    template_name = 'app/login.html'

"""
class Account_login(View):
    def post(self, request, *arg, **kwargs):
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            user = User.objects.get(username=username)
            login(request, user)
            return redirect('/')
        return render(request, 'login.html', {'form': form,})

    def get(self, request, *args, **kwargs):
        form = LoginForm(request.POST)
        return render(request, 'login.html', {'form': form,})

account_login = Account_login.as_view()
"""

def index(request):
    """
    トップページ
    """
    file_obj = FileUpload.objects.all()
    context = {
        'file_obj': file_obj,
    }
    return render(request, 'app/index.html', context)

def detail(request, pk):
    """
    詳細ページ
    """
    file_value = get_object_or_404(FileUpload, id=pk)
    try:
        # utf-8に対応
        df = pd.read_csv(file_value.upload_file.path, index_col=0)
    except UnicodeDecodeError:
        # cp932に対応
        df = pd.read_csv(file_value.upload_file.path, index_col=0, encoding='cp932')
    context = {
            'file_value': file_value,
            'df': df,
    }
    return render(request, 'app/detail.html', context)

def analyze(request, pk):
    """
    解析結果ページ
    """
    file_value = get_object_or_404(FileUpload, id=pk)
    analyze = Analyze()
    df = analyze.run(file_value.upload_file.path, pk)
    file_value = get_object_or_404(FileUpload, id=pk)
    context = {
            'file_value': file_value,
            'df': df,
    }
    return render(request, 'app/analyze.html', context)

def new_file(request):
    """
    ファイルアップロードページ
    """
    if request.method == "POST":
        form = FileUploadForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('app:index')
    else:
        form = FileUploadForm()
    return render(request, 'app/new_file.html', {'form': form })

app/templates/app/analyze.html
{% extends 'app/base.html' %}

{% block content %}
    <div class="list">
        <h2>解析結果</h2>
        <br>
        <a href="{% url 'app:index' %}">戻る</a>
        <br>
        <!-- 各インスタンス属性の要素を取得 -->
        <p>ダウンロード：<a href="{{ file_value.analyzed_file.url }}">{{file_value.analyzed_file_name }}</a></p>
        <br>
        <!-- 読み込んだCSVファイルをテーブル形式で表示 -->
        <table border="1">
            <tr>
                <td>index</td>
                {% for columns, item in df.iteritems %}
                    <th>{{ columns }}</th>
                {% endfor %}
            </tr>
            {% for index, rows in df.iterrows %}
                <tr>
                    <th>{{ index }}</th>
                    {% for row in rows %}
                        <td>{{ row }}</td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

<!--
<!doctype html>
<html>
        <head>
                <title>Yency - 家計簿アプリ</title>
        </head>
        <body>

            <h2>解析結果</h2>
            <br>

            <a href="{% url 'app:index' %}">戻る</a>
            <br>

            <p>ダウンロード：<a href="{{ file_value.analyzed_file.url }}">{{file_value.analyzed_file_name }}</a></p>
            <br>

            <table border="1">
                <tr>
                    <td>index</td>
                    {% for columns, item in df.iteritems %}
                        <th>{{ columns }}</th>
                    {% endfor %}
                </tr>
                {% for index, rows in df.iterrows %}
                    <tr>
                        <th>{{ index }}</th>
                        {% for row in rows %}
                            <td>{{ row }}</td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>

        </body>
</html>
-->

app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html>
       <head>
              <title>Yency - 家計簿アプリ</title>
              <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
              <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
              <link rel="preconnect" href="https://fonts.gstatic.com">
              <link href="https://fonts.googleapis.com/css2?family=Libre+Franklin:ital,wght@1,900&display=swap" rel="stylesheet">
              <link rel="stylesheet" href="{% static 'css/yency.css' %}">
       </head>
       <body>
              <div class="page-header">
                     <h2 style="display:inline;"><a href="/"><span>Y</span>ency</a></h2>
                     <p style="display:inline;">Convert CSV (by yen-note for Windows 10) into EXCEL.</p>
              </div>
              <ul class="topnav">
                     <li><a href="/">Home</a></li>
                     <li><a href="{% url 'app:new_file' %}">Upload</a></li>
                     <!--<li class="loginuser">logout</li>-->
                     <!--<li class="loginuser">username: <span>{{ user.username }}</span></li>-->
              </ul>
              {% block content %}
              {% endblock %}
              </div>
       </body>
</html>

app/templates/app/detail.html
{% extends 'app/base.html' %}

{% block content %}
    <div class="list">
        <h2>詳細</h2>
        <div style="text-align: right;">
            <a class="btn_return" href="{% url 'app:index' %}">戻る</a>
        </div>
        <!-- 各インスタンス属性の要素を取得 -->
        <!-- <p>アップロード日：{{ file_value.created_at }}</p>-->
        <p><a class="btn_item" href="{{ file_value.upload_file.url }}">ダウンロード</a>：{{file_value.upload_file_name }}</p>
        <br>
        <!-- 読み込んだCSVファイルをテーブル形式で表示 -->
        <table border="1">
            <tr>
                <td>index</td>
                {% for columns, item in df.iteritems %}
                    <th>{{ columns }}</th>
                {% endfor %}
            </tr>
            {% for index, rows in df.iterrows %}
                <tr>
                    <th>{{ index }}</th>
                    {% for row in rows %}
                        <td>{{ row }}</td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

<!--
<!doctype html>
<html>
        <head>
                <title>Yency - 家計簿アプリ</title>
        </head>
        <body>

            <h2>CSVファイル内容詳細</h2>
            <br>

            <a href="{% url 'app:index' %}">戻る</a>
            <br>

            <p>アップロード日：{{ file_value.created_at }}</p>
            <p>ダウンロード：<a href="{{ file_value.upload_file.url }}">{{file_value.upload_file_name }}</a></p>
            <br>

            <table border="1">
                <tr>
                    <td>index</td>
                    {% for columns, item in df.iteritems %}
                        <th>{{ columns }}</th>
                    {% endfor %}
                </tr>
                {% for index, rows in df.iterrows %}
                    <tr>
                        <th>{{ index }}</th>
                        {% for row in rows %}
                            <td>{{ row }}</td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>

        </body>
</html>
-->

app/templates/app/index.html
{% extends 'app/base.html' %}

{% block content %}
       <div class="list">
              <br>
              {% if file_obj %}
                     {% for file in file_obj %}
                            <div>
                                   {{ file.created_at }}
                                   {{ file.title }}
                                   <a class="btn_item" href="{% url 'app:detail' pk=file.id %}" role="button">詳細</a>
                                   <a class="btn_item" href="{% url 'app:analyze' pk=file.id %}" role="button">解析実行</a>
                            </div>
                     {% endfor %}
              {% else %}
                     <h3>現在ファイルはありません</h3>
              {% endif %}
       </div>
{% endblock %}

<!--
{% load static %}
<!DOCTYPE html>
<html>
       <head>
              <title>Yency - 家計簿アプリ</title>
              <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
              <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
              <link rel="preconnect" href="https://fonts.gstatic.com">
              <link href="https://fonts.googleapis.com/css2?family=Libre+Franklin:ital,wght@1,900&display=swap" rel="stylesheet">
              <link rel="stylesheet" href="{% static 'css/yency.css' %}">
       </head>
       <body>
              <div class="page-header">
                     <h2 style="display:inline;"><a href="/"><span>Y</span>ency</a></h2>
                     <p style="display:inline;">Convert CSV (by yen-note for Windows 10) into EXCEL.</p>
              </div>
              <ul class="topnav">
                     <li><a class="active" href="/">Home</a></li>
                     <li><a href="{% url 'app:new_file' %}">Upload</a></li>
              </ul>
              <div class="list">
                     <br>
                     {% if file_obj %}
                            {% for file in file_obj %}
                                   <div>
                                          {{ file.created_at }}
                                          {{ file.title }}
                                          <a class="btn_item" href="{% url 'app:detail' pk=file.id %}" role="button">詳細</a>
                                          <a class="btn_item" href="{% url 'app:analyze' pk=file.id %}" role="button">解析実行</a>
                                   </div>
                                   <br>
                            {% endfor %}
                     {% else %}
                            <h3>現在ファイルはありません</h3>
                     {% endif %}
              </div>
       </body>
</html>
-->

app/templates/app/login.html
<!DOCTYPE html>
<html lang="ja">
  <body>
    {% if form.errors  %}
    <p>ユーザーID, パスワードが一致しません．</p>
    {% endif %}
    <form method="POST" action="{% url 'app:login' %}">
      {% csrf_token %}
      <label>ユーザーID</label>
      {{ form.username }}
      {{ form.username.errors }}
      <label>パスワード</label>
      {{ form.password }}
      {{ form.password.errors }}
      <button type = "submit">ログイン</button>
    </form>
  </body>
</html>

app/templates/app/logout.html
ログアウトしました。

app/templates/app/new_file.html
{% extends 'app/base.html' %}

{% block content %}
    <div class="list">
        <h2>新しいファイルを登録</h2>
        <div style="text-align: right;">
            <a class="btn_return" href="{% url 'app:index' %}">戻る</a>
        </div>
        <form enctype="multipart/form-data" action="{% url 'app:new_file' %}" method="POST">
            {% csrf_token %}
            <div>
                <label for="title">Title: {{ form.title }}</label>
            </div>
            <div>
                <label for="file">{{ form.upload_file }}</label>
            </div>
            <button class="btn_item" type="submit">保存</button>
        </form>
    </div>
{% endblock %}

<!--
<!doctype html>
<html>
        <head>
            <title> Yency - 家計簿アプリ</title>
        </head>
        <body>
            <a href="{% url 'app:index' %}">TOPへ戻る</a>
            <br>
            <form enctype="multipart/form-data" action="{% url 'app:new_file' %}" method="POST">
                {% csrf_token %}
                {{ form }}
                <button type="submit">保存</button>
            </form>
        </body>
</html>
-->